[COMMON]
port                            = 8109
# 是否开启双向HTTPS认证
open_tls                        = false
# 这里使用原配置的阿里云凭证，实际使用时应替换成自己的
ali_app_id = ""
ali_app_secret = ""
# 可以选择使用MySQL作为消息队列或使用Kafka
mysql_as_mq = true
consume_priority = 1
open_cache = true
max_retry_count = 4 # 最大重试次数
# 邮箱配置，应替换为自己的邮箱信息
email_account = "xxxxxxxx@qq.com"
email_auth_code = "xxxxxxx"

# 当使用Docker Compose环境时，服务名会用作主机名
[MySQL]
url                             = "127.0.0.1:3306"
# 外部访问使用 localhost:3306
# url                           = "localhost:3306"
user                            = "root"
pwd                             = "root"
db_name                         = "msgcenter_db"

[Redis]
url                             = "192.168.123.103:6379"
# 外部访问使用 localhost:6379
# url                           = "localhost:6379"
pwd                             = "123456"
db                              = 0

[Kafka]
brokers                         = ["192.168.123.103:9092"]
# 外部访问使用 localhost:9092
# brokers                       = ["localhost:9092"]
# Kafka不需要密码，使用SASL时才需要
# pwd                           = "kafkapass"

# 各优先级队列配置
[kafka.topics.low]
name = "low_msg"   # Topic名称
priority = 1         # 优先级：1=低，2=中，3=高
ack = 0                 # 确认机制：0=不等待确认，1=等待leader确认，-1=等待所有副本确认
async = true            # 是否异步发送
offset = -1             # 消费者偏移量：-2=从头开始消费，-1=从最新消息开始消费
group_id = "low"     # 消费者组ID，可选

[kafka.topics.middle]
name = "middle_msg"
priority = 2
ack = 0
async = true
offset = -1
group_id = "middle"

[kafka.topics.high]
name = "high_msg"
priority = 3
ack = 0
async = true
offset = -1
group_id = "high"

[kafka.topics.retry]
name = "retry_msg"
priority = 4
ack = 0
async = true
offset = -1
group_id = "retry"